### ISSUE TITLE
No DeepSleep after Start/Restart

### ISSUE THREAD

**Issue by derKief** [bq/aquaris-U-Plus#1]
with new ROM version 2.2.0 there is a bug with deepsleep after device start/restart.
If device is started/restarted and not unlocked immediately afterwards it doenst go into deepsleep.
This is the exact same issue/bug as [X5 Plus device has](https://github.com/bq/aquaris-X5-plus/issues/1) with newest ROM 2.1.0
So this is not device specific and was no problem with previous versions.

**Comment by Kra1o5** [comment]
Hi @derKief,

As I just comment on this issue: https://github.com/bq/aquaris-X5-plus/issues/1

You can contact our support team through this link: https://www.bq.com/en/support/ and will attend your query as soon as possible.

Regards,

**Comment by derKief** [comment]
outdated
